version: "3.9"
services:
  database:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ethereum
      - POSTGRES_USER=ethereum
      - POSTGRES_PASSWORD=ethereum
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
